### ISSUE TITLE
About MVA

### ISSUE THREAD

**Issue by ApocalypsezZ** [3dlg-hcvc/DuoduoCLIP#5]
<img width="1075" alt="企业微信截图_f3482d75-b8fc-4f80-8f8e-fd6b171b8fc4" src="https://github.com/user-attachments/assets/fc324df1-2d77-45f1-893e-933e61c48a08">

I have some questions.

Does "not using MVA" mean using the average? 
Why is the effect of three-layer MVA worse than not using MVA?

Thanks for your great work again.

**Comment by hanhung** [comment]
Hello, for Table 3 all 12 attention layers in the model are trainable the difference is that for **-MVA**, the images are processed in parallel so the attention is only between patches of the same images and the embeddings are averaged at the end. For **+MVA** the attention layers are modified so that patches are also able to attend across the different multi-views.

As for Table 4, all of these methods use **+MVA**. However, the number of trainable layers are varied for ablation. 12 layers (full) is the same configuration as **+MVA** in Table 3. 6 layers and 3 layers means that only the last 6 and 3 attention layers are trainable respectively. So **-MVA** in Table 3 does better than 3 layers in Table 4 due to having more trainable layers.
